logging:
  config: classpath:logback-spring.xml
  file:
    path: /Users/muyuanqiang/logs/sentry
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制